#!/bin/sh
# Reads project-root .env and writes native secrets before compile.
# Xcode resolves $(GOOGLE_MAPS_API_KEY) in Info.plist from xcconfig too early /
# inconsistently versus Run Scripts — the Swift constants file always matches the
# key used when AppDelegate loads GMSServices.
set -e
ENV_FILE="${SRCROOT}/../.env"
XCCONFIG_OUT="${SRCROOT}/Flutter/GeneratedSecrets.xcconfig"
SWIFT_OUT="${SRCROOT}/Runner/GoogleMapsSecrets.swift"

VAL=""
if [ -f "$ENV_FILE" ]; then
  LINE=$(grep -E '^GOOGLE_MAPS_API_KEY=' "$ENV_FILE" | tail -1 || true)
  VAL=${LINE#GOOGLE_MAPS_API_KEY=}
  VAL=$(printf '%s' "$VAL" | sed 's/^"//;s/"$//')
  VAL=$(printf '%s' "$VAL" | sed "s/^'//;s/'$//")
fi

mkdir -p "${SRCROOT}/Flutter"

swift_literal=$(
  PYTHON=$(command -v python3 || command -v python || true)
  if [ -n "$PYTHON" ]; then
    export VAL
    "$PYTHON" - <<'PY' || printf '%s' '""'
import json, os
print(json.dumps(os.environ.get("VAL", "") or ""))
PY
  else
    printf '%s' '""'
  fi
)

cat >"$SWIFT_OUT" <<EOF
import Foundation

// Generated by ios/scripts/generate_secrets_from_env.sh — do not edit by hand.
enum GoogleMapsSecrets {
    static let apiKey: String = ${swift_literal}
}
EOF

printf 'GOOGLE_MAPS_API_KEY=%s\n' "$VAL" >"$XCCONFIG_OUT"
