import Foundation

// Generated by ios/scripts/generate_secrets_from_env.sh — do not edit by hand.
enum GoogleMapsSecrets {
    static let apiKey: String = "AIzaSyCO7-MMlSQlXQ1usB4-MIm_V1VIKzFjLng"
}
